### ISSUE TITLE
missing from for imports

### ISSUE THREAD

**Issue by Konfekt** [bfrg/vim-qf-diagnostics#2]
On Ubuntu 22.04 Vim 8.2.2204 complains that

```vim
# plugin/qfdiagnostics.vim (lines 11-12)
import autoload '../autoload/qfdiagnostics/popup.vim'
import autoload '../autoload/qfdiagnostics/highlight.vim'
```

lack a  from attribute.

**Comment by bfrg** [comment]
Well, I'm not surprised about the error because initially the `import` statement had a different syntax. See for example here what it looked like: https://github.com/vim/vim/blob/v8.2.2204/runtime/doc/vim9.txt#L955-L967.

Version 8.2.2204 is already 4 years old. I don't think I want to support such an old version.

**Comment by llbit** [comment]
I had the same issue with Vim 8.2 yesterday but upgrading to 9.1 fixed it for me. Vim 8.2 is the version shipped in Ubuntu 22.04 LTS.

**Comment by Konfekt** [comment]
How did you upgrade it? It does not seem to be in the official repos and the only trustable resort seems compiling it

**Comment by llbit** [comment]
I just cloned vim from GitHub and compiled it from source:
```
git clone https://github.com/vim/vim.git
cd vim
make
sudo make install
```

**Comment by Konfekt** [comment]
Yes, that's what I did as well, though I had to make some adjustment for Python support, which some plug-ins require. Just wondering how these upgrades for LTS distros work, as git is somewhat recent on Opensuse Leap, but Vim, likely like Ubuntu, rather stale.
